apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30080 # Auth service accessible at localhost:30080
    - port: 8081
      targetPort: metrics
      protocol: TCP
      name: metrics
      nodePort: 30081 # Metrics accessible at localhost:30081
