apiVersion: v1
kind: Service
metadata:
  name: {{ include "worker-go.name" . }}
  labels:
    {{- include "worker-go.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "worker-go.name" . }}
  ports:
    - name: http
      port: {{ .Values.healthPort }}
      targetPort: http
