apiVersion: v1
kind: Service
metadata:
  name: cache-service
  labels:
    app: cache-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: grpc
  selector:
    app: cache-service
---
apiVersion: v1
kind: Service
metadata:
  name: cache-service-metrics
  labels:
    app: cache-service
    service: metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: metrics
  selector:
    app: cache-service
