apiVersion: batch/v1
kind: Job
metadata:
  name: profile-api-stress-job
spec:
  template:
    spec:
      containers:
        - name: k6
          image: grafana/k6:latest
          command:
            ["k6", "run", "--out", "json=/tmp/results.json", "/scripts/test.js"]
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: profile-api-stress-configmap
                  key: API_URL
          volumeMounts:
            - name: test-script
              mountPath: /scripts
            - name: results
              mountPath: /tmp
      volumes:
        - name: test-script
          configMap:
            name: profile-api-stress-configmap
            items:
              - key: TEST_SCRIPT
                path: test.js
        - name: results
          emptyDir: {}
      restartPolicy: Never
  backoffLimit: 0
